#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements

sed 's/127.0.0.1/127.0.0.2/' /etc/hosts | sudo tee /etc/hosts > /dev/null
if grep -q "facebook.com" /etc/hosts; then
    sed 's/.*facebook.com/8.8.8.8 facebook.com/' /etc/hosts | sudo tee /etc/hosts > /dev/null
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
