#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements

# Remove the default localhost entry for 127.0.0.1
sudo sed -i '/127.0.0.1[[:space:]]\+localhost/d' /etc/hosts > /dev/null

# Add new localhost entry with 127.0.0.2
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Add facebook.com entry with 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
